name: Serveo SSH Tunnel with User and Data Cache (Root, Password Only)

on:
  workflow_dispatch:

jobs:
  serveo:
    runs-on: namespace-profile-test

    steps:
      # Step 1: Enable Namespace cache for /data (instant persistent cache)
      - name: Enable /data cache (Namespace Cache Volume)
        if: always()
        continue-on-error: true
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            /data

      # Step 2: Create 'serveo' user (optional, keep for reference)
      - name: Create 'serveo' user
        if: always()
        continue-on-error: true
        run: |
          echo "Creating user 'serveo'..."
          sudo useradd -m -s /bin/bash serveo || echo "User already exists"
          echo "serveo:serveo" | sudo chpasswd
          echo "User 'serveo' created with password 'serveo'."

      # Step 3: Reset root password
      - name: Reset root password
        if: always()
        continue-on-error: true
        run: |
          echo "root:serveo" | sudo chpasswd
          echo "Root password reset complete."

      # Step 4: Enable root login via SSH
      - name: Allow root login via SSH
        if: always()
        continue-on-error: true
        run: |
          echo "Enabling root login for SSH..."
          sudo sed -i.bak -E 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart || true
          sudo service ssh status || true

      # Step 5: Start SSH service
      - name: Start SSH service
        if: always()
        continue-on-error: true
        run: |
          echo "Starting SSH service..."
          sudo service ssh start || true
          sudo service ssh status || true

      # Step 6: Start Serveo reverse SSH tunnel as root
      - name: Start Serveo reverse SSH tunnel
        if: always()
        continue-on-error: true
        timeout-minutes: 350
        run: |
          echo "Starting Serveo reverse SSH tunnel as root with password only..."

          # Run the tunnel as root using password authentication
          sshpass -p 'serveo' ssh -o StrictHostKeyChecking=no \
            -R my-root-1208:22:localhost:22 serveo.net -v
